# This workflow will thoroughly test the build system
name: Complete build system test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends git make optipng gettext gnome-shell libglib2.0-bin

    - name: Check assets are optimised and no extra files have been committed
      run: |
        # Check all assets are space optimised
        make prune compress COMPRESSLEVEL="-o0"

    - name: Check translation generation works
      run: |
        make translations
        git restore po/

    - name: Test extension builds from a clean slate
      run: |
        make build

    - name: Test extension is valid and able to be uploaded
      run: |
        make check

    - name: Check no extra files have been committed
      run: |
        # Clean up files (Shouldn't have to do anything)
        make clean
        # Fail if any files generated by last step that haven't been committed
        if [ ! -z "$(git status --porcelain)" ]; then exit 1; fi

    - name: Check release workflow is functional
      run: |
        #Fake gtk4-builder-tool to echo to avoid errors due to no gtk4 packages
        echo "echo \$@" | sudo tee /usr/bin/gtk4-builder-tool; sudo chmod +x /usr/bin/gtk4-builder-tool
        make release

    - name: Test extension installs
      run: |
        make install
